### ISSUE TITLE
Cannot add a resource file in Visual Studio

### ISSUE THREAD

**Issue by damienbod** [aspnet/Localization#117]
A resource file cannot be created in Visual Studio in a MVC6 application. It's missing from the menu

Greetings Damien

**Comment by hishamco** [comment]
Which version of VS are you running?

**Comment by damienbod** [comment]
VS 2015
Version 14.0.23107.0 D14REL

**Comment by hishamco** [comment]
I think the VS Tooling for Localization in not fully support
@kirthik your comment please

**Comment by joeaudette** [comment]
I'm facing the same problem, I thought this would be possible with the new beta8 tooling but there is no option to add .resx files either in a web project or a class library package project

**Comment by kirthik** [comment]
We don't have support in VS to add `.resx` files to ASP.NET 5 applications yet. @rustd can tell you more details.

**Comment by joeaudette** [comment]
I notice that if  I add an existing resx file into a project file tree, ie I created a folder AppResources in a web app project and put a .resx file there that I made previously in VS 2013. VS 2015 automatically adds a .designer.cs file and it makes all the access "internal". Based on the very limited sample in this repo I thought maybe I could just package .resx files as content and use them directly, but in that case I don't want VS 2015 to add .designer.cs files because the resx files as content may come from other projects and just be packaged as content along with views and js files. So if that content is added to my webapp ie via nuget then my web app should not generate .designer.cs files.

Is there a way I can tell VS 2015 to ignore a folder and not auto generate .designer.cs files if I put .resx files in the folder? ie like the current localization sample has no designer.cs files

Using a different approach I tried adding an existing resx file to a class library project thinking I could then access the resources the old static way @namespace.ResourceFile.ResourceKey but since the designer file is marked as internal I cannot access it from another project and VS 2015 won't let me change the access to public.

**Comment by kirthik** [comment]
VS adds auto-generated `.designer.cs` for `.resx` files that don't have locale info in them. Example - VS generates `test.designer.cs` for `test.resx` but it does not auto generate for `test.fr-Fr.resx`.

**Comment by joeaudette** [comment]
Thank you @kirthik that opened my eyes and now I see, it makes perfect sense. I just need to rename my .resx files as .en-US.resx and then I can use the approach shown in the sample and won't have any .designer.cs files.

**Comment by rustd** [comment]
https://github.com/aspnet/Templates/issues/199 is tracking this.
