### ISSUE TITLE
Support localized resources formats

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#12]
Is there possibility to store the localized resources - key / value pairs - in other formats like json instead of rely on the old resx files

/cc @DamianEdwards

**Comment by DamianEdwards** [comment]
Yes absolutely. That is the intent of creating the new `IStringLocalizer` abstraction. An implementation can store them wherever it wants. We will only be shipping the `ResourceManager` implementation for now though.

**Comment by hishamco** [comment]
So is the issue #3 can be fixed used an implementation of ```IStringLocalizer``` such as ```ResourceManagerStringLocalizer ```?

**Comment by DamianEdwards** [comment]
@hishamco correct. You can write your own class that implements `IStringLocalizer` that retrieves the strings from whatever location you want. Then you would register that in the DI container (i.e. in your `ConfigureServices` method) so that anything asking for an `IStringLocalizer` will get your implementation.

**Comment by hishamco** [comment]
Thanks @DamianEdwards
