### ISSUE TITLE
Moving 'CultureInfoCache' to Microsoft.AspNet.Localization namespace

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#201]
I'm not quite sure why ```CultureInfoCache``` still exists in ```Microsoft.Extensions.Globalization``` why the intend of this namespace to hold all the objects that are related to globalization stuff which was already removed.

**Comment by Eilon** [comment]
CultureInfo is used for globalization and localization - they are in some sense two sides of the same coin.

@DamianEdwards do you care much either way? In my mind Globalization (as it is now) makes more sense because the CultureInfos are about breadth of cultures and being culture-agnostic, as opposed to the localization middleware and resource loading which is about targeting a specific culture.

**Comment by DamianEdwards** [comment]
Yeah I'm fine to leave it where it is.

**Comment by hishamco** [comment]
Thanks
