### ISSUE TITLE
Unexpected behavior in Custom RequestCultureProvider

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#212]
While i'm trying to push a PR to Entropy repo, I faced a strange issue with custom ```RequestCultureProvider```. I created a simple ```JsonRequestCultureProvider```, it becomes the winning provider and the cultures retrieved successfully except the values can't be localized,I dig into that with no luck, seems the entire localization resource lookup is disabled, the source is available [here](https://github.com/hishamco/Entropy/tree/localization)

**Comment by hishamco** [comment]
@DamianEdwards can you please have a look to this, because I'm not sure if this a bug?!!

**Comment by Eilon** [comment]
@ryanbrandenburg can you investigate this?

**Comment by hishamco** [comment]
Any updates regarding this

**Comment by Eilon** [comment]
The last 2 days were the weekend :smile:

**Comment by hishamco** [comment]
I forget the time difference between US and middle east :smile:

**Comment by ryanbrandenburg** [comment]
I gave this one a look and it doesn't appear to be a bug. The problem is [here](https://github.com/hishamco/Entropy/blob/localization/samples/Localization.ConfigurationRequestCultureProvider/Startup.cs#L13). In order for your resources to be found automatically your "Base" namespace MUST be the same as your project name. Thus, since this project is named "Localization.ConfigurationRequestCultureProvider" and the namespace containing "Startup" is only "ConfigurationRequestCutlureProvider" it won't be found. Simply add "Localization" to the front and it should work fine.

I agree that this point isn't exactly made clear at the moment, but I believe someone is working on the documentation, so hopefully it'll save someone in the future some pain.

**Comment by hishamco** [comment]
Thanks so much @ryanbrandenburg
