### ISSUE TITLE
Question: How can you use a different resource file in a satellite assembly from a class library project?

### ISSUE THREAD

**Issue by ghost** [aspnet/Localization#214]
I my case, the default Resources.resx file from the class library is always used. The localized versions like Resource.de.resx are ignored.

Any hint?

**Comment by hishamco** [comment]
I think it's duplicate for #154

**Comment by pepevc** [comment]
My class library is a "dnx" assembly, not a regular one.

**Comment by hishamco** [comment]
@Eilon is this blocked by #157

**Comment by Eilon** [comment]
@pepevc what exactly is the scenario here? Can you provide more info about what is in each project, what the code is trying to do, what doesn't work, and what you were expecting?

**Comment by pepevc** [comment]
Pick for instance https://github.com/aspnet/identity. That project contains
a resx file for error messages. I would like the localization framework to
pick the correct culture resx file automatically.

**Comment by Eilon** [comment]
@pepevc so you have a solution like this:

1. **MyLibrary**
 - Has Class1.cs with a method `GetData()` that loads resources from:
 - Class1.resx (has neutral en-US resources)
 - Class1.fr-fr.resx (has French resources)
 - Class1.ja-jp.resx (has Japanese resources)
2. **MyApp**
 - Has Program.cs that calls `Class1.GetData()`
 
And you're saying that when it called `GetData` that it always picks up English, no matter what?

**Comment by pepevc** [comment]
@Eilon yes, basically that's it. I am following the Identity project as an example. Have a look at their IdentityErrorDescriber class and the AssemblyInfo.cs.

I reproduced something similar with with a dnx class library project but my aspnet project fails to make my class library load anything besides the main resx file.

Not a big issue as I will end up doing the localization in the webapp, but the bug? is there.

**Comment by Eilon** [comment]
@pepevc thanks for the extra info!

@ryanbrandenburg can you take a look?

**Comment by ryanbrandenburg** [comment]
@DamianEdwards could you opine on this? It was my impression that not having resources from satellite assemblies was by design.

**Comment by MrWinky** [comment]
"_It was my impression that not having resources from satellite assemblies was by design_."

I hope not!  Because is a major problem that breaks  SOLID architecture principles (for loose coupling and tight cohesion).  

For example:

1.   EF 7 is kept in it's own project.  MyProject.Data.EntityFramework
2.  Business logic layer objects which use the strings  MyProject.BLL.ViewModels
2.  The web portal (with startup.cs) is in it's own project MyProject.Portal

This is pretty standard N tier architecture.   

Each of these projects need the resx files.   

However,   If I am forced to place  MyProject.Resources.resx in the web portal app, now I have a circular reference problem.   Because Portal project is dependent on  EntityFramework and ViewModel projects (as it should be).   Conversely,  EntityFramework and BLL need those SAME resource strings and now becomes dependent on the Portal project!?.

**Comment by Eilon** [comment]
An alternative to this is to expose the resources via a helper class that has a type with properties on it that exposes all the properties. Might not be as simple as what is being asked for here, but it will work, and perhaps one could argue that it has cleaner separation of concerns (embedded resources can be considered to be an implementation detail of how a type implements resources).

**Comment by MrWinky** [comment]
Wait.   How can this not be a defect in design? A bug really.   Because the
injector is supposed to take the path - but it doesn't use namespaces or
references instead,    just a relative file path.

You are absolutely  right about the separation of concerns. However web is
beautifully situated for resx files  because based upon the language in the
request header, the   developer just only has to map one name to  the same
string in  different languages.


Therefore, instead of Microsoft  making us   write what the RESX injector
member  does for views and data annotations in a "helper" class,  (and I
have no idea how we would know to switch languages)  why not just fix the
injector class options parameter to take the reference and use reflection
or whatever they need to do to get the RESX files.  My god - if they could
do it for relative path they certainly can do it for a reference




On May 24, 2016, at 3:41 PM, Eilon Lipton <notifications@github.com> wrote:

An alternative to this is to expose the resources via a helper class that
has a type with properties on it that exposes all the properties. Might not
be as simple as what is being asked for here, but it will work, and perhaps
one could argue that it has cleaner separation of concerns (embedded
resources can be considered to be an implementation detail of how a type
implements resources).

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/aspnet/Localization/issues/214#issuecomment-221383890>

**Comment by Eilon** [comment]
@MrWinky this is something we will look into, just not at this immediate time.

**Comment by ryanbrandenburg** [comment]
This is not a scenario which the current system supports, however we did a little refactoring of `ResourceManagerStringLocalizerFactory` to make it easier to subclass and implement this behavior yourself. An example of what that might look like can be found at aspnet/Entropy#159.
