### ISSUE TITLE
Can't load shared resources 

### ISSUE THREAD

**Issue by Weboholics** [aspnet/Localization#247]
We have a project with both shared resources and view resources. These resources are stored in separate folders -  "Resources/Global" and "Resources/Views"

We made a new simple web project with a repro. home/index page shows a view resource and a shared resource.

[The sourcecode](http://weboholics.se/content/localizationTest.rar)

The View resources loads correctly but the Shared(Global) resource won't work.

Hints:
We can see that the IStringLocalizer instance "_localizer" in HomeController has a "suspicious" value in field _resourceBaseName -	`LocalizationTest.Resources.Views.Weboholics.LocalizationTest.Resources.Global.Button`

**Comment by Eilon** [comment]
@pranavkm can you take a quick look and see what's going on here?

**Comment by pranavkm** [comment]
@Weboholics the `LocalizationOptions` on `AddLocalization` is the same instance as the one in `AddViewLocalization`. The `ResourcePath` that you specify in `services.AddLocalization(options => { options.ResourcesPath = "Resources/Global"; });` gets overwritten by `.AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix, options => { options.ResourcesPath = "Resources/Views"; });` which is why you're seeing this behavior.

One alternative to continue placing global resources independent of view resources would be to use string based overload of `IStringLocalizerFactory`. Something along the lines of `stringLocalizerFactory.Create("Resources.Global.Button", location: null)`. The other alternative would be to place global and view resources under the same directory structure and move the `Button` type to a namespace that would allow it to be looked up relative to the specified namespace.

cc @DamianEdwards for thoughts on this.

**Comment by Weboholics** [comment]
We tried your suggestions but couldn't find a solution that works with both shared resources and view resources. Generally we think that the mixing of paths and parts of namespaces is too complex. 

What we simply want to be able to do:
1. Use a default namespace like Weboholics.ProductName (two parts) in our products
2. Keep our Shared Resources and View Resources separate (preferable)
3. Be able to inject both types of resources into Razor Views
4. Be able to inject Shared Resources into Controllers

Some thoughts:
It seems like that the lookup of resources is based on namespaces; therefore options.ResourcesPath should instead be "options.NameSpace" and be absolute, not relative - in our example options.NameSpace="Weboholics.LocalizationTest.Resources.Global".

**Comment by pranavkm** [comment]
@Weboholics - I agree the path -> namespace conversion has a couple of gotchas that aren't immediately obvious.
