### ISSUE TITLE
IViewLocalizer returns the wrong language when default is non-English

### ISSUE THREAD

**Issue by Rick-Anderson** [aspnet/Localization#277]
See this on [SO](http://stackoverflow.com/questions/38147076/iviewlocalizer-returns-the-wrong-language)
Also  [this ](https://docs.asp.net/en/latest/fundamentals/localization.html#comment-2842901156)comment in DISQUS 
I want to use Spanish as the default language of my application and English as optional. I configured it all up. If I have two seperate resx files for both Spanish and English the website runs as expected. But I don't want to include Spanish resx file, I want use the in-code strings (ie. Localizer). When I only include English resx file, the website uses it, ignores in-code strings.

**Comment by hishamco** [comment]
Do you mean if the current culture isn't english the localization doesn't fallback properly?

**Comment by Rick-Anderson** [comment]
I think that's what they are trying to say.

**Comment by Rick-Anderson** [comment]
@kichalla  please review

**Comment by hishamco** [comment]
@Rick-Anderson we need a repo to reproduce the issue if there's, it's great if anyone have an issue related to any of the aspnet repositories to post them in github, so the team can ask more questions about it and see a demo that reproduce the issue, to simplify the process

**Comment by hishamco** [comment]
I used the [LocalizationOrigin](https://github.com/branciat/LocalizationOrigin) project that provided in issue #276 as a sample with the modification that is available in the StackOverflow, I got these results:

![de](https://cloud.githubusercontent.com/assets/3237266/17860630/b6562636-6896-11e6-9784-d24d43a9838a.PNG)

![en](https://cloud.githubusercontent.com/assets/3237266/17861209/cb9cdcc2-6898-11e6-9d99-dee15c2a88ba.PNG)

This implies that ```IViewLocalizer``` returns the correct result

**Comment by Rick-Anderson** [comment]
Closing the issue until we get a repo. Perhaps we need a machine with the OS culture non-english.

**Comment by SherleyDev** [comment]
I think the problem is that I don't use cookies. I use URL friendly localization. http://localhost/es/account/login or http://localhost/accont/login for Spanish and http://localhost/en/account/login for English.

For URL friendly localization I follow the method described in this SO answer: http://stackoverflow.com/questions/35829426/optionally-override-request-culture-via-url-route-in-an-asp-net-core-1-0-applica

Thank you!

**Comment by hishamco** [comment]
@SherleyDev Is that mean he using a ```CustomRequestCultureProvider```?

**Comment by christianheld** [comment]
I am the author of the SO post: 
I have added a small repro on https://github.com/christianheld/ResourceManagerIssue

The app default language is `en`, but running on a `de-DE` version of Windows. Also the app seems to work as excpected on Azure. I think it might be related to the OS language.

**Comment by hishamco** [comment]
@christianheld I run it on Windows 10 version 10.0.10240 on both ```netcoreapp1.0``` and ```net451``` I got the right result

UI Culture: en
Hello World!
UI Culture: de
Hallo Welt!

**Comment by Rick-Anderson** [comment]
@hishamco I think the problem is you need to run this on a non-English machine. For example, @christianheld  ran it on a de-DE version of Windows and I think someone else ran it on an Spanish version.

**Comment by hishamco** [comment]
Yep, hope someone else try this on non-English version of Windows, Unfortunately I have an English one to verify if this a bug or not

**Comment by Eilon** [comment]
@ryanbrandenburg can you try to repro this on a non-English OS?

**Comment by ryanbrandenburg** [comment]
@christianheld I ran your project on a de-DE version of windows and got the output I would expect:
```
UI Culture: en
Hello World!
UI Culture: de
Hallo Welt!
```

Is [this](https://github.com/christianheld/ResourceManagerIssue) the exact setup you had when you ran into this issue? Can you tell me what output you get when you do `dotnet --version` on the command line?

**Comment by christianheld** [comment]
@ryanbrandenburg yes, this is the exact setup. 
`dotnet --version` says `1.0.0-preview2-003121`

**Comment by ryanbrandenburg** [comment]
@christianheld I was able to get the output:
```
UI Culture: en
Hello World!
UI Culture: de
Hello World!
```
by adding `"language": "de",` to the ResourseManagerIssue `project.json`. This is the equivalent of adding `[assembly: NeutralResourcesLanguage("de")]` to AssemblyInfo.cs. What this does is set "de" as the neutral culture, meaning that instead of looking for the resource described by `SR.de.resx` like we normally would, the `ResourceManager` instead looks for the resource described by `SR.resx`, and since your example doesn't have it it returns the key.

So, in order to resolve your problem either:

1. Double check that you aren't setting "language" in the project.json, don't have `[assembly: NeutralResourcesLanguage("en-us")]` in Properties/AssemblyInfo.cs or some other way of setting NeutralResourcesLanguage.
2. Explicitly set the language to "de" (or whatever default you want) and be sure that your resx for that language is "SR.resx" and not "SR.de.resx".

If there is a chance that your project will be used by or deployed to an OS which doesn't share your language settings (which seems likely) it would seem to me that 2 is the safe option.

Does that solve your problem?

**Comment by Rick-Anderson** [comment]
@ryanbrandenburg this looks like something I should add to the document.

**Comment by ryanbrandenburg** [comment]
@Rick-Anderson I agree, especially since this is the second time I've seen `language` causing basically this confusion. Let me know over email if you need anything from me with regards to that.

**Comment by christianheld** [comment]
@ryanbrandenburg Thank you very much for your help: Problem solved!

In my special case adding one of `language: "en"` or `[assembly: NeutralResourcesLanguage("en")]` solves the problem. I think this is because in my project I want to have English as default language instead of German even though running and compiling on de-DE Windows.

**Comment by Rick-Anderson** [comment]
@christianheld  can you help me draft the instructions I need to add to the [ loc doc](https://docs.asp.net/en/latest/fundamentals/localization.html)

**Comment by ryanbrandenburg** [comment]
Sounds like this is done then.
