### ISSUE TITLE
Where are the autogen properties in asp.net core localizers?

### ISSUE THREAD

**Issue by holgerleichsenring** [aspnet/Localization#289]
There are some questions raised due to implementation of ILocalizer interface:

It's introduced like this via Dependency Injection (from docs):

    Route("api/[controller]")]
    public class AboutController : Controller
    {
        private readonly IStringLocalizer<AboutController> _localizer;

        public AboutController(IStringLocalizer<AboutController> localizer)
        {
            _localizer = localizer;
        }

        [HttpGet]
        public string Get()
        {
            return _localizer["About Title"];
        }
    }
These things have to be accomplished:

 - IStringLocalizer has to be used with the type of the class specified as generic
 - localizer instance has to be called with a string information
Some thoughts/questions about it:

 - Why is it necessary to have the type of the class defined for that interface? Looks like an IoC necessity to me.
 - Method _localizer[“default text”] is some kind of sub optimal because
     - The defaults actually should also be defined by professional translaters.
     - I don’t want to have magic strings flying around, especially no string with punctation marks
     - In case that a string couldn’t be found I would like to be informed about it. This is pretty easy when using constant names like “TITLE_ABOUT” or “title_about” if you prefer lowercase names. In this way I can only obtain it when the language is different from default that it stays English.
     - Why do we loose the straight procedure with ResourceManager’s automatic generated code and their properties?

find blog entry about that topic [here](http://codingsoul.de/2016/09/26/where-are-the-autogen-properties-in-asp-net-core-localizers/).

**Comment by hishamco** [comment]
The `IStringLocalizer` is not the only one used to localized strings, you can use the `IViewLocalizer` via `inject` directive in the views, also you can use `HtmlLocalizer` for localizing `HtmlString`.
> Why is it necessary to have the type of the class defined for that interface? Looks like an IoC necessity to me.

The generic type that you passed in used to provide strings for, because every type should have a resource file .resx, so the localization APIs will be able to get the values back to the localizer, for more information you can look into [StringLocalizer&lt;T&gt;](https://github.com/aspnet/Localization/blob/b52e33caa7927093dc3ec540fd3282f4f69ae169/src/Microsoft.Extensions.Localization.Abstractions/StringLocalizerOfT.cs)
Of course the DI is very important to access the registered `IStringLocalizer` implementation which is define here https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/LocalizationServiceCollectionExtensions.cs#L65

> The defaults actually should also be defined by professional translaters

Regarding the translation, you can send the resource files to be translated, everything else, 
Last thing if you mean by the auto gen properties those properties that are generated by Visual Studio, those may useful for the APIs themselves, have a look to this https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L233, https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/Resources.resx#L120.
This line https://github.com/aspnet/Localization/blob/dev/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L192 may looks interesting to you to see how the `ResourceManagerStringLocalizer` get the resource values, and don't forget this the only implementation that we have out of the box, but if you look again into this [sample](https://github.com/aspnet/Entropy/tree/dev/samples/Localization.EntityFramework) you will realize that the localization APIs not relying into resx files (auto gen properties)

**Comment by Eilon** [comment]
@holgerleichsenring your thoughts are all valid. This loc system was designed based on our experience looking at other loc systems and trying to capture what we thought were the most valuable features. But it certainly isn't The One True Localization System. Apps are free to use RESX / *.designer.cs files as they did before, or they can use this new system, or they can build out their own custom system.

**Comment by holgerleichsenring** [comment]
Thanks for comprehensive answers! Two suggestions: 

 - It would be helpful to have built-in support of constants of the resource manager's output right in the ILocalizer<> interface to avoid magic strings when calling for translation
 - People tend to have exactly one resx file for translation. Being able to configure the strategy would also be perfect.

**Comment by ryanbrandenburg** [comment]
@holgerleichsenring both of your final suggestions are possible within our current system (if I've understood you correctly).

1. It's entirely possible to do `stringLocalizer["TITLE_ABOUT"]` instead of using the default text of the title, simply define it that way in your resx file. Just keep in mind that if a particular key is missing for a culture and all its children (including the default culture) the result will be "TITLE_ABOUT".
2. If you wish to only have one resx file you can just do `public AboutController(IStringLocalizer<SharedResource> localizer) {` where `SharedResource` is an empty class with a corresponding resx file. You could also inject both a `SharedResource` localizer and an `AboutController` localizer if you want to have some common elements but also keep page specific things from crowding your page.

**Comment by ryanbrandenburg** [comment]
I think we've addressed everything here, but feel free to re-open if I missed something.
