### ISSUE TITLE
validation attributes default translation wrong culture

### ISSUE THREAD

**Issue by do0om** [aspnet/Localization#294]
Hi,

I can't understand how translation for validation attributes  works.
By default, when I run on my french machine and I set current culture to french, validation messages are in french.
When I run it on an english server while setting current culture to french, validation messages are in english.
Is this behavior expected?
I tried to set on my computer (french culture installed) a culture different than the one installed and it sets the validation messages to english.

[sample projet here](https://www.dropbox.com/s/o11hxmwd3xisia6/LocalizationSample.zip?dl=0)

**Comment by hishamco** [comment]
Please have a look to [Localization.StarterWeb](https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb) for more details about localization. 
BTW you need to define a resource file for your validation messages in case you want to localize them, please have a look to shown here https://github.com/aspnet/Entropy/blob/dev/samples/Localization.StarterWeb/Resources/ViewModels/Account/RegisterViewModel.fr.resx#L121

**Comment by do0om** [comment]
Thanks for the sample but it does not explain why it is translating in french without doing anything except calling UseRequestLocalization with french culture (no resources, no AddLocalization, no AddDataAnnotationsLocalization)  and why this is changing depending on computer installed language.

**Comment by hishamco** [comment]
If you talking about the StarterWeb sample it has almost things about localization. Regarding your sample I'm still wonder why the data annotation messages show up on French, while there's no resource file in your project?!! AFAIK the default resx file which is available in CoreFx is English one.
@ryanbrandenburg your thoughts

**Comment by ryanbrandenburg** [comment]
@do0om it appears that you're using the default ValidationAttribute messages. If that's the case and you have no local resx files (which appears to be true based on your zip) then this is being sourced from CoreFX, which is strange, because as @hishamco said they only have one (english) resx file checked in.

I'm spinning up a french VM to test this on, but in the mean time could you try one of the strategies [here](https://github.com/aspnet/Localization/issues/277#issuecomment-246854009) to set the default language for your app and tell me if that stops the issue for you?

**Comment by ryanbrandenburg** [comment]
So, I was able to reproduce this. It seems that ValidationAttributes DO localize their messages based on the installed language of the machine, at least for some languages. The question then becomes how do we get multiple languages of these installed at once and used base on the requesting culture. I believe that that's something to file against CoreFx  since they actually own the validation attributes.

And now that my VM is finally spun up, no, setting the default language doesn't help.

**Comment by do0om** [comment]
Sorry, I could not work on this yesterday, do you still want me to set the default language?
Have you created an issue in the core fx repo?

**Comment by ryanbrandenburg** [comment]
@do0om I think I've got this nailed down now, and I don't think it will require a CoreFX issue. This only happens (that I can find) when you're running `net451`. Projects running under `netcoreapp1.0` don't encounter this, and their validation messages will always (for now) be in English because currently that's the only resource they have.

`net451` apps on the other hand will use the installed language packs to localize as appropriate. So, if your server only has the french language pack installed you won't get a German validation message regardless of your request language. If you install the language packs for the languages you want (and allow them as supported languages) everything should work.

Alternatively if you want to avoid the extra steps in provisioning you can localize the attributes yourself using our standard ErrorMessage system.

**Comment by do0om** [comment]
@ryanbrandenburg  This is strange since my sample is running net461

**Comment by ryanbrandenburg** [comment]
That was bad communication on my part, I didn't mean to imply that net451 was the only framework this would happen for, but that it depends on if you're using a core or non-core framework.

Do the procedures I listed solve your issue?

**Comment by ryanbrandenburg** [comment]
Sorry @do0om that was bad comunication on my part, I meant to imply that having a non-core framework was the only way I knew of of making this happen, not that `net451` was the only version with this problem.

Do the options I listed solve your issue?

**Comment by do0om** [comment]
@ryanbrandenburg no problem for the communication part.

For the solutions : I can't manage to install a new language pack on my system or on my server.
Am I Supposed to download [this](https://www.microsoft.com/fr-FR/download/details.aspx?id=49977) by setting a new language?  It says (translated from french) that the module does not match my operating system language...

I Followed your solution [here](https://github.com/aspnet/Localization/issues/286) to have a shared resource but I can't get this working:
 `[Required(ErrorMessage = "RequiredError")]` 
with 
`.AddDataAnnotationsLocalization(options => {
                options.DataAnnotationLocalizerProvider = (type, factory) =>
                    factory.Create(typeof(SharedResource));
            });` 
and using
` services.AddLocalization(options=> options.ResourcesPath = "Resources");`
and having a resource called SharedResource.fr.resx in Resources Folder

Using ` [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(SharedResource))]`
is the only thing working.

**Comment by ryanbrandenburg** [comment]
@do0om strange that the shared resource didn't work for you, I've created an example of it [here](https://github.com/aspnet/Entropy/tree/rybrande/LocalizationShared), can you confirm that the localization sample I changed in that most recent commit works on your machine then look for any differences between how it's done there and in your project?

**Comment by do0om** [comment]
Your sample is working on my machine, I need more time to investigate why it's not working in my project.

**Comment by do0om** [comment]
@ryanbrandenburg Sorry for the very late reply, I was very busy but I finally took time to examine the sample.
It was not working in my project because I did not have an empty SharedResource class
like this:
`public class SharedResource
    {
    }`
That's what I don't understand, why do I need an empty class for this to work?
When I create SharedResource.fr.resx, it already creates a class behind the scene and everything compiled fine but it did not work.

**Comment by ryanbrandenburg** [comment]
@do0om the .Designer.cs class that you're talking about defaults to being in the namespace of the folder your resource is in, which will confuse the construction of the name of the resource to look for. The empty class avoids this problem, and allows you to keep using the IStringLocalizerFactory.Create(Type) overload, but if you don't like having empty classes around you also have the option of the IStringLocalizerFactory.Create(string basename, string location) overload. You can find examples of using that overload [here](https://github.com/aspnet/Localization/blob/dev/test/LocalizationWebsite/StartupResourcesInClassLibrary.cs#L48).

**Comment by do0om** [comment]
@ryanbrandenburg Ok I understand the empty class trick.
Thank you for all your help.
