### ISSUE TITLE
Dynamic parameters throw exception

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Localization#308]
Here is an example that fails, it's from an MVC view but the same behavior should fail outside too.

```
@inject Microsoft.Extensions.Localization.IStringLocalizer<int> S

@{ 
    dynamic x = "foo";
}

@S["Hello {0}", x]
```

I get 
```
RuntimeBinderException: Cannot apply indexing with [] to an expression of type 'Microsoft.Extensions.Localization.IStringLocalizer<int>'
```

Casting the variable to `object` solves the issue.

**Comment by hishamco** [comment]
You're right, but i'm not sure if it's Localization or CLR bug, because I saw many folks facing the same exception in arrays!!

**Comment by Eilon** [comment]
Moved the bug to here: https://github.com/dotnet/corefx/issues/14752

Don't think we can do much about it. Don't use `dynamic`, it's evil 😄

**Comment by JonHanna** [comment]
I've submitted a fix for the corefx bug. In the meantime, if someone hits something like this then as long as the implementing class injected into `S` implemented the interface directly rather than as explicit implementation then `@((dynamic)S)["Hello {0}", x]` should work because it would force the lookup to happen on the concrete type rather than the interface, which this bug doesn't affect. Since most of the cost of dynamic is per-expression rather than per-type, the performance impact won't be much over that of having had `x` as dynamic in the first place.
