### ISSUE TITLE
Question: How to set cookie name?

### ISSUE THREAD

**Issue by Ponant** [aspnet/Localization#324]
Hi ,
I am trying to set the default culture cookie name and came across a suggestion on GitHub of setting
CookieRequestCultureProvider.DefaultCookieName = "_cultureLocalization";
But how can this work with a static readonly?

What I did so far is a controller-action with the following, which works

`Response.Cookies.Append( CookieRequestCultureProvider.DefaultCookieName, CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(cultureName)), new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) });`

but otherwise setting the name by hand does not work

`Response.Cookies.Append( "myCookie", CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(cultureName)), new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) });`

Please advise if possible

**Comment by hishamco** [comment]
The simple answer is using the `MakeCookieValue` which is available here https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/CookieRequestCultureProvider.cs#L56, FYI you can refer to the code I wrote here https://github.com/aspnet/Localization/blob/dev/test/Microsoft.AspNetCore.Localization.Tests/CookieRequestCultureProviderTest.cs#L55

**Comment by hishamco** [comment]
Sorry @Ponant I thought you wanna set the cookie value, regarding the cookie name you can set the property `CookieName` which is available here https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/CookieRequestCultureProvider.cs#L29

**Comment by Ponant** [comment]
@hishamco , thank you for your prompt answer(s), indeed I was wondering about your first post. Still, in your second I do not see how to set `CookieName `(it is not listed as an option in intellisense).

**Comment by hishamco** [comment]
@Ponant ignore my first post, it was my bad understanding 😄 

> Still, in your second post I do not see how to set CookieName(it is not listed as an option in intellisense without instantiation).

I already refer to the test that using that property, BTW it requires to have an instance of `CookieRequestCultureProvider`
my suggestion is to insert an instance of `CookieRequestCultureProvider` to `RequestCultureProviders` property as shown here https://github.com/aspnet/Localization/blob/dev/samples/LocalizationSample/Startup.cs#L48, in this way you will be able to use your newly created `RequestCultureProvider`

**Comment by Ponant** [comment]
No problem, that happens!
I made it work but I had to refer to a magic string twice, as such
in Startup
` var provider = new CookieRequestCultureProvider()
                {
                    CookieName = "Preferences"
                };
                options.RequestCultureProviders.Insert(0, provider);`
and in the controller-action
`Response.Cookies.Append(
                 "Preferences",
                 CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(cultureName)),
                 new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) });`
If you have a more clever way then I will go for it, otherwise thank you for your time. :)

**Comment by hishamco** [comment]
You can use `const` instead of magic string. Regarding the code in the controller action are you trying to set the cookie expiration per culture? Please let me understand the case, so I can give you the better answer

**Comment by Ponant** [comment]
I am trying to set a one-year cookie after the user has selected the preferred culture. If he changes the culture, the cookie should be changed. I expect the above to do just that, right?

**Comment by hishamco** [comment]
Yep, it does, but you use the selected `RequestCulture` in `IRequestCultureFeature` instead of instantiating `RequestCulture` every time, you can refer to this https://github.com/hishamco/LanguageSwitcherTagHelper/blob/master/TagHelpers/LanguageSwitcherTagHelper.cs#L41

**Comment by Ponant** [comment]
Hisham,
I think you are using this ViewContext for a TagHelper, whereas I am working on a controller. So, you mean that to improve performance it would be better to rewrite my logic from View to controller? If so, I welcome some guidance. Here is my code in case you can see some improvements. The only thing I do not want to use is a drop down list to select a language; rather I want to redirect to a page where a list of cultures is listed. So here is my code:

Layout
`                        <a asp-controller="Language" asp-action="Index" asp-route-returnUrl="@Context.Request.Path">
                            <span class="glyphicon glyphicon-globe"></span>
                        </a>` 

View Model

```
    public class LanguageViewModel
    {
        public string ReturnUrl { get; set; }
        public IList<CultureInfo> Cultures { get; set; }
    }
```

Language Index View

```
@using System.Globalization
@model LocalizationGarage.Models.LanguageViewModel
@{
    ViewData["Title"] = "Language";
}
@foreach (var item in Model.Cultures)
{
    <form asp-controller="Language" asp-action="Index"
          asp-route-returnurl="@Model.ReturnUrl"
          asp-route-cultureName="@item.Name" method="post">
        <button>@item.DisplayName</button>
    </form>
}
```

Controller
```

public class LanguageController : Controller
    {
        private readonly IList<CultureInfo> _supportedCultures;

        public LanguageController(IOptions<RequestLocalizationOptions> requestLocalizationOptions)
        {
            _supportedCultures = requestLocalizationOptions.Value.SupportedCultures;
        }
        [HttpGet]
        public IActionResult Index(string returnUrl = null)
        {
            var model = new LanguageViewModel()
            {
                Cultures = _supportedCultures,
                ReturnUrl = returnUrl
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(LanguageViewModel model, string cultureName = null)
        {
            if (ModelState.IsValid)
            {
                Response.Cookies.Append(
                 "Preferences",
                 CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(cultureName)),
                 new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) });

                return RedirectToLocal(model.ReturnUrl);
            }
            ModelState.AddModelError("", "Could not change language");
            return View(model);
        }
        private IActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                //TODO
                return RedirectToAction("Index", "Home");
            }
        }
    }
```

**Comment by hishamco** [comment]
@Ponant it's not the matter of the `ViewContext` you can use it in the controller, please refer to this https://github.com/aspnet/Localization/blob/dev/samples/LocalizationSample/Startup.cs#L68, regarding the culture dropdown list this your choice, according your case, in general looks fine, but it would be nice if you are using default request culture instead of creating a new instance below:
```csharp
Response.Cookies.Append(
                 "Preferences",
                 CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(cultureName)),
                 new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) });
```

**Comment by Ponant** [comment]
I see what you mean, but I do not succeed in passing something else than "new RequestCulture(cultureName))". This is because the `requestCulture = context.Features.Get<IRequestCultureFeature>().RequestCulture`) is the culture that is there before the user selects the culture he wants. Once the user selects a culture, I see no other option than setting the (new) culture as above.

**Comment by hishamco** [comment]
Yes you 're right, it's my bad again 😄, because the `context.Features.Get<IRequestCultureFeature>().RequestCulture` will retrieve the current selected culture, so I think it is fine to stay with what you are come up with except using `const` instead of magic string
I apologize coz my mind working with a lot of think from the beginning 😄

**Comment by Ponant** [comment]
Hisham,
no worries, at least you clarified to me quite a few things. Thank you again for your time and dedication.

**Comment by hishamco** [comment]
You 're welcome, hope this got fixed now 😄

**Comment by ryanbrandenburg** [comment]
@Ponant could you clarify what (if any) problem/question you still have?

**Comment by Ponant** [comment]
@ryanbrandenburg , well @hishamco clarified a lot and confirmed what I thought, so we can close the discussion.
Perhaps the only remaining question is:
Why do we need to set the cookieName in two places? So far what I did with the help of @hishamco is to set the cookieName in Startup, but then I had to further refer to the cookieName in the action of a controller (see code above). While this works well, I wonder why the Localization API does not allow you to set the CookieName in one place only (Startup) and make a call directly to a "CustomCookie" when you want to persist a cookie in an action. My question, thus, is why things have been made a such?

In any case, I would recommend to add to the docs on Localization a few lines on how to create a custom cookie. On this aspect the docs are poor, whereas any dev who wants to go to production would like to name his cookies.
Cheers

**Comment by hishamco** [comment]
IMHO `DefaultCookieName` is a `static` to share the default cookie name which is set by the localization API, I don't think `CookieName` should be `static` too, because if anyone change its value it will affect all the instances. So that's why you need to refer to your custom cookie name as magic string or `const` which is the better IMHO.
@ryanbrandenburg let me know your thoughts about this

**Comment by hardhub** [comment]
@hishamco 

It is readonly:
`public static readonly string DefaultCookieName = ".AspNetCore.Culture";`

For it is much more interesting how to get value which is set as CookieName in provider.
In other words what should be used to create cookie... because cookie should be set manually.

**Comment by hishamco** [comment]
@hardhub if you are interesting to the custom cookie name you can use:
```csharp
((CookieRequestCultureProvider)requestCultureFeature.Provider.GetType()).CookieName
```

**Comment by hardhub** [comment]
@hishamco 

What is it? None compilable code? :)
> ((CookieRequestCultureProvider)requestCultureFeature.Provider.GetType()).CookieName

In any case this feature cannot be used:
this.HttpContext.Features.Get<IRequestCultureFeature>()

It has property for only triggered provider...

**Comment by hishamco** [comment]
Please refer to the sample to access localization feature https://github.com/aspnet/Localization/blob/dev/samples/LocalizationSample/Startup.cs#L64-L65

**Comment by hardhub** [comment]
@hishamco 

Please read my previous post carefully... I said it cannot be used and said why.
But I will try to explain... Provider property of that feature will be null if no no provider is triggered.
But it still can be added to options and be configured with cookie name.

**Comment by hishamco** [comment]
@hardhub FYI localization by default has 3 built-in providers injected by default, I don't know why you re think the provider property will be `null`?!!

**Comment by hardhub** [comment]
@hishamco 

If no one of these providers will be triggered and default locale will be used then Provider will be null.
It can be if you provide logic to enable/disable any such provider from config file.
Because only accept language most likely will be triggered always (in case of browser).
But if it is custom http client then it is not mandatory.

The single possible way I see for now is to derive all providers from `RequestCultureProvider` as well as it is now for for all framework providers... Also we will need to initialize Options properties for each provider.
`
AcceptLanguageHeaderRequestCultureProvider provider = new ...
provider.MaximumAcceptLanguageHeaderValuesToTry = 5;
provider.Options = options;
`
In addition we will have to add AlwaysCultureProvider derived from the same base.. and add this provider in the end of collection. It will trigger always (in case when no one else triggered) and will be available from feature. The single purpose of this provider to give us original options.

Then we will have to known all added providers, and try to cast it and access its Options property. Then we will be able to enumerate RequestCultureProviders collection and check for cookie based provider and get its CookieName.

To a bit simplify walking in collection we can derive default providers and add some interface exposing Options property.

So it is a trick and too much complicated to be a good solution...

**Comment by hishamco** [comment]
@hardhub I got confused!! in your first comment you are looking for the custom cookie name, now the scenario is become little bit different, anyhow, I don't think the provider will be null because if the cookie & querystring is not triggered the AcceptLanguageHeader will trigger.

While you are talking about custom cookie you could remove the default `CookieRequestCultureProvider` and insert a new one with the a custom name in the position 0

**Comment by hardhub** [comment]
@hishamco 
I have explained all very well.. So I cannot add anything new info.. all answers are there.
