### ISSUE TITLE
Unable to run the LocalizationSample

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#326]
@ryanbrandenburg after changing to VS 2017, I'm not able to run the LocalizationSample, when I run `dotnet run` I got this error:

LocalizationSample.csproj : error MSB4040: There is no target in the project.

The build failed. Please fix the build errors and run again.

**Comment by ryanbrandenburg** [comment]
@hishamco it is unclear to me what exactly the issue is here. You shouldn't need to run `dotnet new` to run the LocalizationSample since it already exists, so I assume you mis-typed. For the record I'm able to successfully launch and visit the LocalizationSample from VS2017 (granted, I'm using the very newest version).

**Comment by hishamco** [comment]
Sorry for the typo, I run `dotnet run`. I update my VS yesterday to update 4 but I didn't try it, but still wondering why it doesn't work from the command line?!!

**Comment by ryanbrandenburg** [comment]
The CLI now requires that you provide a TFM if your project targets multiple frameworks, so you can't do `dotnet run` on projects like this anymore, you have to do `dotnet run -f netcoreapp1.1`. That said, the error message given when this happens does nothing to make that clear, so I'm going to file a bug against the CLI to that effect.

**Comment by ryanbrandenburg** [comment]
There's already an issue for this: dotnet/cli#4684.

**Comment by hishamco** [comment]
Thanks a lot @ryanbrandenburg
