### ISSUE TITLE
Fix the docs

### ISSUE THREAD

**Issue by RonPenton** [aspnet/Localization#370]
I just spent an hour debugging code with the CookieRequestCultureProvider. The reason?

The docs (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) indicate that the following is a valid cookie string:

`c='en-UK'|uic='en-US'`

It is not. The presence of the quotation marks causes the provider to fail. Silently, mind you. So you have no idea why it's failing, just that it's failing. 

A) Fix the docs, please. Such a stupid error wasted an hour of my life that I'm never going to get back.

B) Please make the methods not fail silently. Silent failures are the worst thing since Jersey Shore. If the cookie named ".AspNetCore.Culture" exists but fails to parse, you can be 99.999% certain that someone is attempting to use a culture but has formatted it wrong. You can save them time, frustration, and hair follicles by throwing up an exception for this exceptional circumstance. Who wouldn't want to help other humans not waste hours of their time on something trivially simple, after all? Be the heroes you are destined to be. Fix this, for all of humanity.

**Comment by hishamco** [comment]
A) @RonPenton you're right there's no quotation in the actual localization format, so I made a PR to fix the docs https://github.com/aspnet/Docs/pull/3393

B) May be we need kind of logging instead of throwing exception in the [`ParseCookieValue`](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/CookieRequestCultureProvider.cs#L76), but this may applicable for other `RequestCultureProvider`s

**Comment by hishamco** [comment]
@RonPenton it got fixed in the commit https://github.com/aspnet/Docs/commit/e1403188650a1d66aef4b98ba634355454e525a7

thanks

**Comment by Eilon** [comment]
@hishamco thanks for fixing the docs! Closing this bug because you opened https://github.com/aspnet/Localization/issues/372 to track having a better logging experience for the issue.

I don't think that throwing an exception is necessarily a good idea here because it would potentially create a scenario where an "innocent" client could poison itself accidentally if it ever got a bad cookie somehow.

**Comment by hishamco** [comment]
I will make a PR for the raised bug soon ..

**Comment by hishamco** [comment]
@Eilon how can we using logging in the static method `ParseCookieValue()`? perhaps throwing the exception is the easiest way unless there a good way to use DI in static method

**Comment by Eilon** [comment]
@hishamco I'm not sure we want an exception because this isn't a fatal or even dangerous error. We'd have to find a way to pass the ILogger through to the method.

**Comment by hishamco** [comment]
Yep that 's what i'm thinking about
