### ISSUE TITLE
Dynamically changing Culture in-flight of a Request

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/Localization#426]
I like the fact that the current locale is no longer tied to a thread in the RequestCulture feature and that you can just get at the current context. 

But... - it looks like there is no way to set the request locale in flight without doing a redirect? If you want to truly dynamically change the locale as part of a request or custom mechanism without creating a new provider that has to be applied globally, it looks like there's no way to do this which is really limiting.

I'm referencing the help from here:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization#setting-the-culture-programmatically

This code shows how to do this, but it looks the only way you can change the current request language is by re-running the request, which is pretty limiting. Global changes are fine and well, but sometimes you may need to manage request language as part of the request flow - without having to refresh the entire page. 

It seems to me the easy fix would be to allow modifying the culture instead of the current read-only setting.

```cs
var requestCulture = HttpContext.Features.Get<IRequestCultureFeature>();
requestCulture.RequestCulture.Culture = new CultureInfo(localeId);
requestCulture.RequestCulture.UICulture = requestCulture.RequestCulture.Culture;        
```

Seems like and artificial limiter to have the culture/ui culture read-only. Given that this is now a per request mechanism I can't see any reason why this should be read-only.

**Comment by hishamco** [comment]
I think this a design decision to change the request cultures from within the request culture provider(s)

/cc @pranavkm @ryanbrandenburg

**Comment by Eilon** [comment]
You can theoretically set the request culture and current culture at any time by doing exactly what the RequestLocalizationMiddleware does:

https://github.com/aspnet/Localization/blob/8b03ee8c81b61a852a586740c4db7b09c17f5e76/src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs#L132-L134

Because it's all "just code," you can run whatever you want, whenever you want.

But, keep in mind, that doesn't mean that the app will necessarily work the way you expect! Some components may have already captured the request culture and won't be aware that another component changed it. Some may have already used the request culture to generate some data/messages/content, and they will not regenerate that content if the culture changes.

This is why by default the culture is set just once, very early in the request, at a time that is most likely to be before any other component of importance tried to use it.
