### ISSUE TITLE
LocalizationSample Error

### ISSUE THREAD

**Issue by hishamco** [aspnet/Localization#5]
I'm getting this error message "No service for type 'Microsoft.Framework.Runtime.IApplicationEnvironment' has been registered" when i'm trying to run LocalizationSample

**Comment by DamianEdwards** [comment]
Most likely caused by today's build breaks. Working from source can be unreliable some days. Seems to be working fine for me now and on CI.

**Comment by hishamco** [comment]
@DamianEdwards still facing the same issue :(

**Comment by DamianEdwards** [comment]
@hishamco OK this is likely caused by you not having a beta5-* version of the DNX on your system. Unfortunately we shipped a bad setup in Visual Studio 2015 RC that puts the incorrect DNVM on your system path pointing to the wrong myget feed, so updating your DNX is much harder than it should be.

Try the following:
  1. Remove the DNVM paths from your system-level PATH environment variable (one will point to program files, the other will be %USERPROFILE%\.dnx\bin)
  1. Follow [these instructions](https://github.com/aspnet/home#upgrading-dnvm-or-running-without-visual-studio) to install DNVM into your user profile
  1. Open a new command prompt and verify that you have the latest version of DNVM by running `dnvm`. The version reported under the ASCII art should be v1.0.0-beta5-something
  1. Install the latest DNVM from the myget feed with the following command: `dnvm upgrade -u`
    1. Note: the `-u` installs from the unstable feed which is on myget, rather than from nuget.org
  1. If you want the Core CLR version as well, install that with the following command: `dnvm install default -r coreclr -u`
  1. Run `dnvm list` and verify the versions you have installed and that the `default` alias points to the latest beta5 version for full x86 CLR
  1. Open the sln again in Visual Studio, let it restore and try to run the sample

**Comment by hishamco** [comment]
@DamianEdwards I didn't install VS 2015 RC, I had VS 2015 CTP 6, but i'm using Visual Studio Code for running the sample. FYI I already have 1.0.0-beta5-11502 clr x86 installed, also it's set as default one

**Comment by DamianEdwards** [comment]
Can you try upgrading your DNX and trying again please?

On Fri, May 8, 2015 at 12:02 PM, Hisham Abdullah Bin Ateya <
notifications@github.com> wrote:

> @DamianEdwards <https://github.com/DamianEdwards> I didn't install VS
> 2015 RC, I had VS 2015 CTP 6, but i'm using Visual Studio Code for running
> the sample. FYI I already have 1.0.0-beta5-11502 clr x86 installed, also
> it's set as default one
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aspnet/Localization/issues/5#issuecomment-100329344>.
>



-- 
Cheers,
Damian

**Comment by hishamco** [comment]
Sure

**Comment by hishamco** [comment]
@DamianEdwards I update dnvm to 1.0.0-beta5-11739 and I got an DirectoryNotfoundException 'wwwroot', I removed webroot property from project.json and it works fine :)

Thanks Damian

**Comment by henkmollema** [comment]
@hishamco adding an empty `wwwroot` folder in the root of your application will fix that too.

**Comment by hishamco** [comment]
@henkmollema thanks, but i already removed the ```webroot``` property from project.json, because there's no files needed to be in ```wwwroot```

**Comment by hishamco** [comment]
@DamianEdwards the issue still exist, by adding an empty ```wwwroot``` folder it will get fix
